# ================================================================
# Updated CIS_TASKS Configuration (Specific List)
# ================================================================

CIS_TASKS = [
    # Section 1
    {"id": "1.1.1", "enabled": True, "desc": "Ensure 'Enforce password history' is set to '24 or more password(s)' (Automated)"},
    {"id": "1.1.2", "enabled": True, "desc": "Ensure 'Maximum password age' is set to '365 or fewer days, but not 0' (Automated)"},
    {"id": "1.1.3", "enabled": True, "desc": "Ensure 'Minimum password age' is set to '1 or more day(s)' (Automated)"},
    # {"id": "1.1.4", "enabled": True, "desc": "Ensure 'Minimum password length' is set to '14 or more character(s)' (Automated)"},
    # {"id": "1.1.5", "enabled": True, "desc": "Ensure 'Password must meet complexity requirements' is set to 'Enabled' (Automated)"},
    # {"id": "1.1.6", "enabled": True, "desc": "Ensure 'Relax minimum password length limits' is set to 'Enabled' (Automated)"},
    # {"id": "1.1.7", "enabled": True, "desc": "Ensure 'Store passwords using reversible encryption' is set to 'Disabled' (Automated)"},
    # {"id": "1.2.1", "enabled": True, "desc": "Ensure 'Account lockout duration' is set to '15 or more minute(s)' (Automated)"},
    # {"id": "1.2.2", "enabled": True, "desc": "Ensure 'Account lockout threshold' is set to '5 or fewer invalid logon attempt(s), but not 0' (Automated)"},
    # {"id": "1.2.3", "enabled": True, "desc": "Ensure 'Allow Administrator account lockout' is set to 'Enabled' (MS only) (Manual)"},
    # {"id": "1.2.4", "enabled": True, "desc": "Ensure 'Reset account lockout counter after' is set to '15 or more minute(s)' (Automated)"},
    
    # Section 2
    # {"id": "2.2.1", "enabled": True, "desc": "Ensure 'Access Credential Manager as a trusted caller' is set to 'No One' (Automated)"},
    # {"id": "2.2.3", "enabled": True, "desc": "Ensure 'Access this computer from the network' is set to 'Administrators, Authenticated Users' (MS only) (Automated)"},
    # {"id": "2.2.4", "enabled": True, "desc": "Ensure 'Act as part of the operating system' is set to 'No One' (Automated)"},
    # {"id": "2.2.6", "enabled": True, "desc": "Ensure 'Adjust memory quotas for a process' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE' (Automated)"},
    # {"id": "2.2.8", "enabled": True, "desc": "Ensure 'Allow log on locally' is set to 'Administrators' (MS only) (Automated)"},
    # {"id": "2.2.10", "enabled": True, "desc": "Ensure 'Allow log on through Remote Desktop Services' is set to 'Administrators, Remote Desktop Users' (MS only) (Automated)"},
    # {"id": "2.2.11", "enabled": True, "desc": "Ensure 'Back up files and directories' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.12", "enabled": True, "desc": "Ensure 'Change the system time' is set to 'Administrators, LOCAL SERVICE' (Automated)"},
    # {"id": "2.2.13", "enabled": True, "desc": "Ensure 'Change the time zone' is set to 'Administrators, LOCAL SERVICE' (Automated)"},
    # {"id": "2.2.14", "enabled": True, "desc": "Ensure 'Create a pagefile' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.15", "enabled": True, "desc": "Ensure 'Create a token object' is set to 'No One' (Automated)"},
    # {"id": "2.2.16", "enabled": True, "desc": "Ensure 'Create global objects' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' (Automated)"},
    # {"id": "2.2.17", "enabled": True, "desc": "Ensure 'Create permanent shared objects' is set to 'No One' (Automated)"},
    # {"id": "2.2.19", "enabled": True, "desc": "Ensure 'Create symbolic links' is set to 'Administrators, NT VIRTUAL MACHINE\\Virtual Machines' (MS only) (Automated)"},
    # {"id": "2.2.20", "enabled": True, "desc": "Ensure 'Debug programs' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.22", "enabled": True, "desc": "Ensure 'Deny access to this computer from the network' to include 'Guests, Local account and member of Administrators group' (MS only) (Automated)"},
    # {"id": "2.2.23", "enabled": True, "desc": "Ensure 'Deny log on as a batch job' to include 'Guests' (Automated)"},
    # {"id": "2.2.24", "enabled": True, "desc": "Ensure 'Deny log on as a service' to include 'Guests' (Automated)"},
    # {"id": "2.2.25", "enabled": True, "desc": "Ensure 'Deny log on locally' to include 'Guests' (Automated)"},
    # {"id": "2.2.27", "enabled": True, "desc": "Ensure 'Deny log on through Remote Desktop Services' is set to 'Guests, Local account' (MS only) (Automated)"},
    # {"id": "2.2.29", "enabled": True, "desc": "Ensure 'Enable computer and user accounts to be trusted for delegation' is set to 'No One' (MS only) (Automated)"},
    # {"id": "2.2.30", "enabled": True, "desc": "Ensure 'Force shutdown from a remote system' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.31", "enabled": True, "desc": "Ensure 'Generate security audits' is set to 'LOCAL SERVICE, NETWORK SERVICE' (Automated)"},
    # {"id": "2.2.33", "enabled": True, "desc": "Ensure 'Impersonate a client after authentication' is set to 'Administrators, LOCAL SERVICE, NETWORK SERVICE, SERVICE' and 'IIS_IUSRS' (MS only) (Automated)"},
    # {"id": "2.2.34", "enabled": True, "desc": "Ensure 'Increase scheduling priority' is set to 'Administrators, Window Manager\\Window Manager Group' (Automated)"},
    # {"id": "2.2.35", "enabled": True, "desc": "Ensure 'Load and unload device drivers' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.36", "enabled": True, "desc": "Ensure 'Lock pages in memory' is set to 'No One' (Automated)"},
    # {"id": "2.2.39", "enabled": True, "desc": "Ensure 'Manage auditing and security log' is set to 'Administrators' (MS only) (Automated)"},
    # {"id": "2.2.40", "enabled": True, "desc": "Ensure 'Modify an object label' is set to 'No One' (Automated)"},
    # {"id": "2.2.41", "enabled": True, "desc": "Ensure 'Modify firmware environment values' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.42", "enabled": True, "desc": "Ensure 'Perform volume maintenance tasks' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.43", "enabled": True, "desc": "Ensure 'Profile single process' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.44", "enabled": True, "desc": "Ensure 'Profile system performance' is set to 'Administrators, NT SERVICE\\WdiServiceHost' (Automated)"},
    # {"id": "2.2.45", "enabled": True, "desc": "Ensure 'Replace a process level token' is set to 'LOCAL SERVICE, NETWORK SERVICE' (Automated)"},
    # {"id": "2.2.46", "enabled": True, "desc": "Ensure 'Restore files and directories' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.47", "enabled": True, "desc": "Ensure 'Shut down the system' is set to 'Administrators' (Automated)"},
    # {"id": "2.2.49", "enabled": True, "desc": "Ensure 'Take ownership of files or other objects' is set to 'Administrators' (Automated)"},
    # {"id": "2.3.1.1", "enabled": True, "desc": "Ensure 'Accounts: Guest account status' is set to 'Disabled' (MS only) (Automated)"},
    # {"id": "2.3.1.2", "enabled": True, "desc": "Ensure 'Accounts: Limit local account use of blank passwords to console logon only' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.1.3", "enabled": True, "desc": "Configure 'Accounts: Rename administrator account' (Automated)"},
    # {"id": "2.3.1.4", "enabled": True, "desc": "Configure 'Accounts: Rename guest account' (Automated)"},
    # {"id": "2.3.2.1", "enabled": True, "desc": "Ensure 'Audit: Force audit policy subcategory settings to override audit policy category settings' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.2.2", "enabled": True, "desc": "Ensure 'Audit: Shut down system immediately if unable to log security audits' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.4.1", "enabled": True, "desc": "Ensure 'Devices: Prevent users from installing printer drivers' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.6.1", "enabled": True, "desc": "Ensure 'Domain member: Digitally encrypt or sign secure channel data (always)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.6.2", "enabled": True, "desc": "Ensure 'Domain member: Digitally encrypt secure channel data (when possible)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.6.3", "enabled": True, "desc": "Ensure 'Domain member: Digitally sign secure channel data (when possible)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.6.4", "enabled": True, "desc": "Ensure 'Domain member: Disable machine account password changes' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.6.5", "enabled": True, "desc": "Ensure 'Domain member: Maximum machine account password age' is set to '30 or fewer days, but not 0' (Automated)"},
    # {"id": "2.3.6.6", "enabled": True, "desc": "Ensure 'Domain member: Require strong (Windows 2000 or later) session key' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.7.1", "enabled": True, "desc": "Ensure 'Interactive logon: Do not require CTRL+ALT+DEL' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.7.2", "enabled": True, "desc": "Ensure 'Interactive logon: Don't display last signed-in' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.7.3", "enabled": True, "desc": "Ensure 'Interactive logon: Machine inactivity limit' is set to '900 or fewer second(s), but not 0' (Automated)"},
    # {"id": "2.3.7.4", "enabled": True, "desc": "Configure 'Interactive logon: Message text for users attempting to log on' (Automated)"},
    # {"id": "2.3.7.5", "enabled": True, "desc": "Configure 'Interactive logon: Message title for users attempting to log on' (Automated)"},
    # {"id": "2.3.7.7", "enabled": True, "desc": "Ensure 'Interactive logon: Prompt user to change password before expiration' is set to 'between 5 and 14 days' (Automated)"},
    # {"id": "2.3.7.8", "enabled": True, "desc": "Ensure 'Interactive logon: Require Domain Controller Authentication to unlock workstation' is set to 'Enabled' (MS only) (Automated)"},
    # {"id": "2.3.7.9", "enabled": True, "desc": "Ensure 'Interactive logon: Smart card removal behavior' is set to 'Lock Workstation' or higher (Automated)"},
    # {"id": "2.3.8.1", "enabled": True, "desc": "Ensure 'Microsoft network client: Digitally sign communications (always)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.8.2", "enabled": True, "desc": "Ensure 'Microsoft network client: Digitally sign communications (if server agrees)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.8.3", "enabled": True, "desc": "Ensure 'Microsoft network client: Send unencrypted password to third-party SMB servers' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.9.1", "enabled": True, "desc": "Ensure 'Microsoft network server: Amount of idle time required before suspending session' is set to '15 or fewer minute(s)' (Automated)"},
    # {"id": "2.3.9.2", "enabled": True, "desc": "Ensure 'Microsoft network server: Digitally sign communications (always)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.9.3", "enabled": True, "desc": "Ensure 'Microsoft network server: Digitally sign communications (if client agrees)' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.9.4", "enabled": True, "desc": "Ensure 'Microsoft network server: Disconnect clients when logon hours expire' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.9.5", "enabled": True, "desc": "Ensure 'Microsoft network server: Server SPN target name validation level' is set to 'Accept if provided by client' or higher (MS only) (Automated)"},
    # {"id": "2.3.10.1", "enabled": True, "desc": "Ensure 'Network access: Allow anonymous SID/Name translation' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.10.2", "enabled": True, "desc": "Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts' is set to 'Enabled' (MS only) (Automated)"},
    # {"id": "2.3.10.3", "enabled": True, "desc": "Ensure 'Network access: Do not allow anonymous enumeration of SAM accounts and shares' is set to 'Enabled' (MS only) (Automated)"},
    # {"id": "2.3.10.5", "enabled": True, "desc": "Ensure 'Network access: Let Everyone permissions apply to anonymous users' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.10.7", "enabled": True, "desc": "Ensure 'Network access: Named Pipes that can be accessed anonymously' is configured (MS only) (Automated)"},
    # {"id": "2.3.10.8", "enabled": True, "desc": "Ensure 'Network access: Remotely accessible registry paths' is configured (Automated)"},
    # {"id": "2.3.10.9", "enabled": True, "desc": "Ensure 'Network access: Remotely accessible registry paths and sub-paths' is configured (Automated)"},
    # {"id": "2.3.10.10", "enabled": True, "desc": "Ensure 'Network access: Restrict anonymous access to Named Pipes and Shares' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.10.11", "enabled": True, "desc": "Ensure 'Network access: Restrict clients allowed to make remote calls to SAM' is set to 'Administrators: Remote Access: Allow' (MS only) (Automated)"},
    # {"id": "2.3.10.12", "enabled": True, "desc": "Ensure 'Network access: Shares that can be accessed anonymously' is set to 'None' (Automated)"},
    # {"id": "2.3.10.13", "enabled": True, "desc": "Ensure 'Network access: Sharing and security model for local accounts' is set to 'Classic - local users authenticate as themselves' (Automated)"},
    # {"id": "2.3.11.1", "enabled": True, "desc": "Ensure 'Network security: Allow Local System to use computer identity for NTLM' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.11.2", "enabled": True, "desc": "Ensure 'Network security: Allow LocalSystem NULL session fallback' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.11.3", "enabled": True, "desc": "Ensure 'Network Security: Allow PKU2U authentication requests to this computer to use online identities' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.11.4", "enabled": True, "desc": "Ensure 'Network security: Configure encryption types allowed for Kerberos' is set to 'AES128_HMAC_SHA1, AES256_HMAC_SHA1, Future encryption types' (Automated)"},
    # {"id": "2.3.11.5", "enabled": True, "desc": "Ensure 'Network security: Do not store LAN Manager hash value on next password change' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.11.6", "enabled": True, "desc": "Ensure 'Network security: Force logoff when logon hours expire' is set to 'Enabled' (Manual)"},
    # {"id": "2.3.11.7", "enabled": True, "desc": "Ensure 'Network security: LAN Manager authentication level' is set to 'Send NTLMv2 response only. Refuse LM & NTLM' (Automated)"},
    # {"id": "2.3.11.8", "enabled": True, "desc": "Ensure 'Network security: LDAP client encryption requirements' is set to 'Negotiate sealing' or higher (Automated)"},
    # {"id": "2.3.11.9", "enabled": True, "desc": "Ensure 'Network security: LDAP client signing requirements' is set to 'Negotiate signing' or higher (Automated)"},
    # {"id": "2.3.11.10", "enabled": True, "desc": "Ensure 'Network security: Minimum session security for NTLM SSP based clients' is set to 'Require NTLMv2 session security, Require 128-bit encryption' (Automated)"},
    # {"id": "2.3.11.11", "enabled": True, "desc": "Ensure 'Network security: Minimum session security for NTLM SSP based servers' is set to 'Require NTLMv2 session security, Require 128-bit encryption' (Automated)"},
    # {"id": "2.3.11.12", "enabled": True, "desc": "Ensure 'Network security: Restrict NTLM: Audit Incoming NTLM Traffic' is set to 'Enable auditing for all accounts' (Automated)"},
    # {"id": "2.3.11.14", "enabled": True, "desc": "Ensure 'Network security: Restrict NTLM: Outgoing NTLM traffic to remote servers' is set to 'Audit all' or higher (Automated)"},
    {"id": "2.3.13.1", "enabled": True, "desc": "Ensure 'Shutdown: Allow system to be shut down without having to log on' is set to 'Disabled' (Automated)"},
    # {"id": "2.3.15.1", "enabled": True, "desc": "Ensure 'System objects: Require case insensitivity for non-Windows subsystems' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.15.2", "enabled": True, "desc": "Ensure 'System objects: Strengthen default permissions of internal system objects' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.1", "enabled": True, "desc": "Ensure 'User Account Control: Admin Approval Mode for the Built-in Administrator account' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.2", "enabled": True, "desc": "Ensure 'User Account Control: Behavior of the elevation prompt for administrators' is set to 'Prompt for consent on the secure desktop' or higher (Automated)"},
    # {"id": "2.3.17.3", "enabled": True, "desc": "Ensure 'User Account Control: Behavior of the elevation prompt for standard users' is set to 'Automatically deny elevation requests' (Automated)"},
    # {"id": "2.3.17.4", "enabled": True, "desc": "Ensure 'User Account Control: Detect application installations and prompt for elevation' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.5", "enabled": True, "desc": "Ensure 'User Account Control: Only elevate UIAccess applications that are installed in secure locations' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.6", "enabled": True, "desc": "Ensure 'User Account Control: Run all administrators in Admin Approval Mode' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.7", "enabled": True, "desc": "Ensure 'User Account Control: Switch to the secure desktop when prompting for elevation' is set to 'Enabled' (Automated)"},
    # {"id": "2.3.17.8", "enabled": True, "desc": "Ensure 'User Account Control: Virtualize file and registry write failures to per-user locations' is set to 'Enabled' (Automated)"},
    
    # Section 5
    {"id": "5.1", "enabled": True, "desc": "Ensure 'Print Spooler (Spooler)' is set to 'Disabled' (DC only)"},
    {"id": "5.2", "enabled": True, "desc": "Ensure 'Print Spooler (Spooler)' is set to 'Disabled' (MS only)"},
    
    # Section 9
    {"id": "9.1.1", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Firewall state' is set to 'On (recommended)' (Automated)"},
    {"id": "9.1.2", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Inbound connections' is set to 'Block (default)' (Automated)"},
    {"id": "9.1.3", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Settings: Display a notification' is set to 'No' (Automated)"},
    {"id": "9.1.4", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Logging: Name' is set to '%SystemRoot%\\System32\\logfiles\\firewall\\domainfw.log' (Automated)"},
    {"id": "9.1.5", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Logging: Size limit (KB)' is set to '16,384 KB or greater' (Automated)"},
    {"id": "9.1.6", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Logging: Log dropped packets' is set to 'Yes' (Automated)"},
    {"id": "9.1.7", "enabled": True, "desc": "Ensure 'Windows Firewall: Domain: Logging: Log successful connections' is set to 'Yes' (Automated)"},
    {"id": "9.2.1", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Firewall state' is set to 'On (recommended)' (Automated)"},
    {"id": "9.2.2", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Inbound connections' is set to 'Block (default)' (Automated)"},
    {"id": "9.2.3", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Settings: Display a notification' is set to 'No' (Automated)"},
    {"id": "9.2.4", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Logging: Name' is set to '%SystemRoot%\\System32\\logfiles\\firewall\\privatefw.log' (Automated)"},
    {"id": "9.2.5", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Logging: Size limit (KB)' is set to '16,384 KB or greater' (Automated)"},
    {"id": "9.2.6", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Logging: Log dropped packets' is set to 'Yes' (Automated)"},
    {"id": "9.2.7", "enabled": True, "desc": "Ensure 'Windows Firewall: Private: Logging: Log successful connections' is set to 'Yes' (Automated)"},
    {"id": "9.3.1", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Firewall state' is set to 'On (recommended)' (Automated)"},
    {"id": "9.3.2", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Inbound connections' is set to 'Block (default)' (Automated)"},
    {"id": "9.3.3", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Settings: Display a notification' is set to 'No' (Automated)"},
    {"id": "9.3.4", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Settings: Apply local firewall rules' is set to 'No' (Automated)"},
    {"id": "9.3.5", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Settings: Apply local connection security rules' is set to 'No' (Automated)"},
    {"id": "9.3.6", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Logging: Name' is set to '%SystemRoot%\\System32\\logfiles\\firewall\\publicfw.log' (Automated)"},
    {"id": "9.3.7", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Logging: Size limit (KB)' is set to '16,384 KB or greater' (Automated)"},
    {"id": "9.3.8", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Logging: Log dropped packets' is set to 'Yes' (Automated)"},
    {"id": "9.3.9", "enabled": True, "desc": "Ensure 'Windows Firewall: Public: Logging: Log successful connections' is set to 'Yes' (Automated)"},

    # Section 17
    {"id": "17.1.1", "enabled": True, "desc": "Ensure 'Audit Credential Validation' is set to 'Success and Failure' (Automated)"},
    {"id": "17.2.1", "enabled": True, "desc": "Ensure 'Audit Application Group Management' is set to 'Success and Failure' (Automated)"},
    {"id": "17.2.5", "enabled": True, "desc": "Ensure 'Audit Security Group Management' is set to include 'Success' (Automated)"},
    {"id": "17.2.6", "enabled": True, "desc": "Ensure 'Audit User Account Management' is set to 'Success and Failure' (Automated)"},
    {"id": "17.3.1", "enabled": True, "desc": "Ensure 'Audit PNP Activity' is set to include 'Success' (Automated)"},
    {"id": "17.3.2", "enabled": True, "desc": "Ensure 'Audit Process Creation' is set to include 'Success' (Automated)"},
    {"id": "17.5.1", "enabled": True, "desc": "Ensure 'Audit Account Lockout' is set to include 'Failure' (Automated)"},
    {"id": "17.5.2", "enabled": True, "desc": "Ensure 'Audit Group Membership' is set to include 'Success' (Automated)"},
    {"id": "17.5.3", "enabled": True, "desc": "Ensure 'Audit Logoff' is set to include 'Success' (Automated)"},
    {"id": "17.5.4", "enabled": True, "desc": "Ensure 'Audit Logon' is set to 'Success and Failure' (Automated)"},
    {"id": "17.5.5", "enabled": True, "desc": "Ensure 'Audit Other Logon/Logoff Events' is set to 'Success and Failure' (Automated)"},
    {"id": "17.5.6", "enabled": True, "desc": "Ensure 'Audit Special Logon' is set to include 'Success' (Automated)"},
    {"id": "17.6.1", "enabled": True, "desc": "Ensure 'Audit Detailed File Share' is set to include 'Failure' (Automated)"},
    {"id": "17.6.2", "enabled": True, "desc": "Ensure 'Audit File Share' is set to 'Success and Failure' (Automated)"},
    {"id": "17.6.3", "enabled": True, "desc": "Ensure 'Audit Other Object Access Events' is set to 'Success and Failure' (Automated)"},
    {"id": "17.6.4", "enabled": True, "desc": "Ensure 'Audit Removable Storage' is set to 'Success and Failure' (Automated)"},
    {"id": "17.7.1", "enabled": True, "desc": "Ensure 'Audit Audit Policy Change' is set to include 'Success' (Automated)"},
    {"id": "17.7.2", "enabled": True, "desc": "Ensure 'Audit Authentication Policy Change' is set to include 'Success' (Automated)"},
    {"id": "17.7.3", "enabled": True, "desc": "Ensure 'Audit Authorization Policy Change' is set to include 'Success' (Automated)"},
    {"id": "17.7.4", "enabled": True, "desc": "Ensure 'Audit MPSSVC Rule-Level Policy Change' is set to 'Success and Failure' (Automated)"},
    {"id": "17.7.5", "enabled": True, "desc": "Ensure 'Audit Other Policy Change Events' is set to include 'Failure' (Automated)"},
    {"id": "17.8.1", "enabled": True, "desc": "Ensure 'Audit Sensitive Privilege Use' is set to 'Success and Failure' (Automated)"},
    {"id": "17.9.1", "enabled": True, "desc": "Ensure 'Audit IPsec Driver' is set to 'Success and Failure' (Automated)"},
    {"id": "17.9.2", "enabled": True, "desc": "Ensure 'Audit Other System Events' is set to 'Success and Failure' (Automated)"},
    {"id": "17.9.3", "enabled": True, "desc": "Ensure 'Audit Security State Change' is set to include 'Success' (Automated)"},
    {"id": "17.9.4", "enabled": True, "desc": "Ensure 'Audit Security System Extension' is set to include 'Success' (Automated)"},
    {"id": "17.9.5", "enabled": True, "desc": "Ensure 'Audit System Integrity' is set to 'Success and Failure' (Automated)"},

    # Section 18
    {"id": "18.1.1.1", "enabled": True, "desc": "Ensure 'Prevent enabling lock screen camera' is set to 'Enabled' (Automated)"},
    {"id": "18.1.1.2", "enabled": True, "desc": "Ensure 'Prevent enabling lock screen slide show' is set to 'Enabled' (Automated)"},
    {"id": "18.1.2.2", "enabled": True, "desc": "Ensure 'Allow users to enable online speech recognition services' is set to 'Disabled' (Automated)"},
    {"id": "18.4.1", "enabled": True, "desc": "Ensure 'Apply UAC restrictions to local accounts on network logons' is set to 'Enabled' (MS only) (Automated)"},
    {"id": "18.4.2", "enabled": True, "desc": "Ensure 'Configure SMB v1 client driver' is set to 'Enabled: Disable driver (recommended)' (Automated)"},
    {"id": "18.4.3", "enabled": True, "desc": "Ensure 'Configure SMB v1 server' is set to 'Disabled' (Automated)"},
    {"id": "18.4.4", "enabled": True, "desc": "Ensure 'Enable Certificate Padding' is set to 'Enabled' (Automated)"},
    {"id": "18.4.5", "enabled": True, "desc": "Ensure 'Enable Structured Exception Handling Overwrite Protection (SEHOP)' is set to 'Enabled' (Automated)"},
    {"id": "18.4.6", "enabled": True, "desc": "Ensure 'NetBT NodeType configuration' is set to 'Enabled: P-node (recommended)' (Automated)"},
    {"id": "18.4.7", "enabled": True, "desc": "Ensure 'WDigest Authentication' is set to 'Disabled' (Automated)"},
    {"id": "18.5.1", "enabled": True, "desc": "Ensure 'MSS: (AutoAdminLogon) Enable Automatic Logon' is set to 'Disabled' (Automated)"},
    {"id": "18.5.2", "enabled": True, "desc": "Ensure 'MSS: (DisableIPSourceRouting IPv6) IP source routing protection level' is set to 'Enabled: Highest protection, source routing is completely disabled' (Automated)"},
    {"id": "18.5.3", "enabled": True, "desc": "Ensure 'MSS: (DisableIPSourceRouting) IP source routing protection level' is set to 'Enabled: Highest protection, source routing is completely disabled' (Automated)"},
    {"id": "18.5.4", "enabled": True, "desc": "Ensure 'MSS: (EnableICMPRedirect) Allow ICMP redirects to override OSPF generated routes' is set to 'Disabled' (Automated)"},
    {"id": "18.5.6", "enabled": True, "desc": "Ensure 'MSS: (NoNameReleaseOnDemand) Allow the computer to ignore NetBIOS name release requests except from WINS servers' is set to 'Enabled' (Automated)"},
    {"id": "18.5.8", "enabled": True, "desc": "Ensure 'MSS: (SafeDllSearchMode) Enable Safe DLL search mode' is set to 'Enabled' (Automated)"},
    {"id": "18.5.9", "enabled": True, "desc": "Ensure 'MSS: (ScreenSaverGracePeriod) The time in seconds before the screen saver grace period expires' is set to 'Enabled: 5 or fewer seconds' (Automated)"},
    {"id": "18.5.12", "enabled": True, "desc": "Ensure 'MSS: (WarningLevel) Percentage threshold for the security event log at which the system will generate a warning' is set to 'Enabled: 90% or less' (Automated)"},
    {"id": "18.6.4.1", "enabled": True, "desc": "Ensure 'Configure multicast DNS (mDNS) protocol' is set to 'Disabled' (Automated)"},
    {"id": "18.6.4.2", "enabled": True, "desc": "Ensure 'Configure NetBIOS settings' is set to 'Enabled: Disable NetBIOS name resolution on public networks' (Automated)"},
    {"id": "18.6.4.4", "enabled": True, "desc": "Ensure 'Turn off multicast name resolution' is set to 'Enabled' (Automated)"},
    {"id": "18.6.7.1", "enabled": True, "desc": "Ensure 'Audit client does not support encryption' is set to 'Enabled' (Automated)"},
    {"id": "18.6.7.2", "enabled": True, "desc": "Ensure 'Audit client does not support signing' is set to 'Enabled' (Automated)"},
    {"id": "18.6.7.3", "enabled": True, "desc": "Ensure 'Audit insecure guest logon' is set to 'Enabled' (Automated)"},
    {"id": "18.6.7.4", "enabled": True, "desc": "Ensure 'Enable authentication rate limiter' is set to 'Enabled' (Automated)"},
    {"id": "18.6.7.5", "enabled": True, "desc": "Ensure 'Enable remote mailslots' is set to 'Disabled' (Automated)"},
    {"id": "18.6.7.6", "enabled": True, "desc": "Ensure 'Mandate the minimum version of SMB' is set to 'Enabled: 3.1.1' (Automated)"},
    {"id": "18.6.7.7", "enabled": True, "desc": "Ensure 'Set authentication rate limiter delay (milliseconds)' is set to 'Enabled: 2000' or more (Automated)"},
    {"id": "18.6.8.1", "enabled": True, "desc": "Ensure 'Audit insecure guest logon' is set to 'Enabled' (Automated)"},
    {"id": "18.6.8.2", "enabled": True, "desc": "Ensure 'Audit server does not support encryption' is set to 'Enabled' (Automated)"},
    {"id": "18.6.8.3", "enabled": True, "desc": "Ensure 'Audit server does not support signing' is set to 'Enabled' (Automated)"},
    {"id": "18.6.8.4", "enabled": True, "desc": "Ensure 'Enable insecure guest logons' is set to 'Disabled' (Automated)"},
    {"id": "18.6.8.5", "enabled": True, "desc": "Ensure 'Enable remote mailslots' is set to 'Disabled' (Automated)"},
    {"id": "18.6.8.6", "enabled": True, "desc": "Ensure 'Mandate the minimum version of SMB' is set to 'Enabled: 3.1.1'"},
    {"id": "18.6.8.7", "enabled": True, "desc": "Ensure 'Require Encryption' is set to 'Enabled'"},
    {"id": "18.6.11.2", "enabled": True, "desc": "Ensure 'Prohibit installation and configuration of Network Bridge on your DNS domain network' is set to 'Enabled' (Automated)"},
    {"id": "18.6.11.3", "enabled": True, "desc": "Ensure 'Prohibit use of Internet Connection Sharing on your DNS domain network' is set to 'Enabled' (Automated)"},
    {"id": "18.6.11.4", "enabled": True, "desc": "Ensure 'Require domain users to elevate when setting a network's location' is set to 'Enabled' (Automated)"},
    {"id": "18.6.14.1", "enabled": True, "desc": "Ensure 'Hardened UNC Paths' is set to 'Enabled, with \"Require Mutual Authentication\", \"Require Integrity\", and \"Require Privacy\" set for all NETLOGON and SYSVOL shares' (Automated)"},
    {"id": "18.6.21.1", "enabled": True, "desc": "Ensure 'Minimize the number of simultaneous connections to the Internet or a Windows Domain' is set to 'Enabled: 3 = Prevent Wi-Fi when on Ethernet' (Automated)"},
    {"id": "18.7.2", "enabled": True, "desc": "Ensure 'Configure Redirection Guard' is set to 'Enabled: Redirection Guard Enabled' (Automated)"},
    {"id": "18.7.3", "enabled": True, "desc": "Ensure 'Configure RPC connection settings: Protocol to use for outgoing RPC connections' is set to 'Enabled: RPC over TCP' (Automated)"},
    {"id": "18.7.4", "enabled": True, "desc": "Ensure 'Configure RPC connection settings: Use authentication for outgoing RPC connections' is set to 'Enabled: Default' (Automated)"},
    {"id": "18.7.5", "enabled": True, "desc": "Ensure 'Configure RPC listener settings: Protocols to allow for incoming RPC connections' is set to 'Enabled: RPC over TCP' (Automated)"},
    {"id": "18.7.6", "enabled": True, "desc": "Ensure 'Configure RPC listener settings: Authentication protocol to use for incoming RPC connections:' is set to 'Enabled: Negotiate' or higher (Automated)"},
    {"id": "18.7.7", "enabled": True, "desc": "Ensure 'Configure RPC over TCP port' is set to 'Enabled: 0' (Automated)"},
    {"id": "18.7.8", "enabled": True, "desc": "Ensure 'Configure RPC packet level privacy setting for incoming connections' is set to 'Enabled' (Automated)"},
    {"id": "18.7.10", "enabled": True, "desc": "Ensure 'Limits print driver installation to Administrators' is set to 'Enabled' (Automated)"},
    {"id": "18.7.11", "enabled": True, "desc": "Ensure 'Manage processing of Queue-specific files' is set to 'Enabled: Limit Queue-specific files to Color profiles' (Automated)"},
    {"id": "18.7.12", "enabled": True, "desc": "Ensure 'Point and Print Restrictions: When installing drivers for a new connection' is set to 'Enabled: Show warning and elevation prompt' (Automated)"},
    {"id": "18.7.13", "enabled": True, "desc": "Ensure 'Point and Print Restrictions: When updating drivers for an existing connection' is set to 'Enabled: Show warning and elevation prompt' (Automated)"},
    {"id": "18.9.3.1", "enabled": True, "desc": "Ensure 'Include command line in process creation events' is set to 'Enabled' (Automated)"},
    {"id": "18.9.4.1", "enabled": True, "desc": "Ensure 'Encryption Oracle Remediation' is set to 'Enabled: Force Updated Clients' (Automated)"},
    {"id": "18.9.4.2", "enabled": True, "desc": "Ensure 'Remote host allows delegation of non-exportable credentials' is set to 'Enabled' (Automated)"},
    {"id": "18.9.7.2", "enabled": True, "desc": "Ensure 'Prevent device metadata retrieval from the Internet' is set to 'Enabled' (Automated)"},
    {"id": "18.9.13.1", "enabled": True, "desc": "Ensure 'Boot-Start Driver Initialization Policy' is set to 'Enabled: Good, unknown and bad but critical' (Automated)"},
    {"id": "18.9.19.2", "enabled": True, "desc": "Ensure 'Configure registry policy processing: Do not apply during periodic background processing' is set to 'Enabled: FALSE' (Automated)"},
    {"id": "18.9.19.3", "enabled": True, "desc": "Ensure 'Configure registry policy processing: Process even if the Group Policy objects have not changed' is set to 'Enabled: TRUE' (Automated)"},
    {"id": "18.9.19.4", "enabled": True, "desc": "Ensure 'Configure security policy processing: Do not apply during periodic background processing' is set to 'Enabled: FALSE' (Automated)"},
    {"id": "18.9.19.5", "enabled": True, "desc": "Ensure 'Configure security policy processing: Process even if the Group Policy objects have not changed' is set to 'Enabled: TRUE' (Automated)"},
    {"id": "18.9.19.6", "enabled": True, "desc": "Ensure 'Continue experiences on this device' is set to 'Disabled' (Automated)"},
    {"id": "18.9.19.7", "enabled": True, "desc": "Ensure 'Turn off background refresh of Group Policy' is set to 'Disabled' (Automated)"},
    {"id": "18.9.20.1.1", "enabled": True, "desc": "Ensure 'Turn off downloading of print drivers over HTTP' is set to 'Enabled' (Automated)"},
    {"id": "18.9.20.1.5", "enabled": True, "desc": "Ensure 'Turn off Internet download for Web publishing and online ordering wizards' is set to 'Enabled' (Automated)"},
    {"id": "18.9.24.1", "enabled": True, "desc": "Ensure 'Enumeration policy for external devices incompatible with Kernel DMA Protection' is set to 'Enabled: Block All' (Automated)"},
    {"id": "18.9.25.1", "enabled": True, "desc": "Ensure 'Configure password backup directory' is set to 'Enabled: Active Directory' or 'Enabled: Azure Active Directory' (Automated)"},
    {"id": "18.9.25.2", "enabled": True, "desc": "Ensure 'Do not allow password expiration time longer than required by policy' is set to 'Enabled' (Automated)"},
    {"id": "18.9.25.3", "enabled": True, "desc": "Ensure 'Enable password encryption' is set to 'Enabled' (Automated)"},
    {"id": "18.9.25.4", "enabled": True, "desc": "Ensure 'Password Settings: Password Complexity' is set to 'Enabled: Large letters + small letters + numbers + special characters' (Automated)"},
    {"id": "18.9.25.5", "enabled": True, "desc": "Ensure 'Password Settings: Password Length' is set to 'Enabled: 15 or more' (Automated)"},
    {"id": "18.9.25.6", "enabled": True, "desc": "Ensure 'Password Settings: Password Age (Days)' is set to 'Enabled: 30 or fewer' (Automated)"},
    {"id": "18.9.25.7", "enabled": True, "desc": "Ensure 'Post-authentication actions: Grace period (hours)' is set to 'Enabled: 8 or fewer hours, but not 0' (Automated)"},
    {"id": "18.9.25.8", "enabled": True, "desc": "Ensure 'Post-authentication actions: Actions' is set to 'Enabled: Reset the password and logoff the managed account' or higher (Automated)"},
    {"id": "18.9.26.1", "enabled": True, "desc": "Ensure 'Allow Custom SSPs and APs to be loaded into LSASS' is set to 'Disabled' (Automated)"},
    {"id": "18.9.28.1", "enabled": True, "desc": "Ensure 'Block user from showing account details on sign-in' is set to 'Enabled' (Automated)"},
    {"id": "18.9.28.2", "enabled": True, "desc": "Ensure 'Do not display network selection UI' is set to 'Enabled' (Automated)"},
    {"id": "18.9.28.3", "enabled": True, "desc": "Ensure 'Do not enumerate connected users on domain-joined computers' is set to 'Enabled' (Automated)"},
    {"id": "18.9.28.4", "enabled": True, "desc": "Ensure 'Enumerate local users on domain-joined computers' is set to 'Disabled' (MS only) (Automated)"},
    {"id": "18.9.28.5", "enabled": True, "desc": "Ensure 'Turn off app notifications on the lock screen' is set to 'Enabled' (Automated)"},
    {"id": "18.9.28.6", "enabled": True, "desc": "Ensure 'Turn off picture password sign-in' is set to 'Enabled' (Automated)"},
    {"id": "18.9.28.7", "enabled": True, "desc": "Ensure 'Turn on convenience PIN sign-in' is set to 'Disabled' (Automated)"},
    {"id": "18.9.30.1.1", "enabled": True, "desc": "Block NetBIOS-based discovery for domain controller location' is set to 'Enabled' (Automated)"},
    {"id": "18.9.33.6.3", "enabled": True, "desc": "Ensure 'Require a password when a computer wakes (on battery)' is set to 'Enabled' (Automated)"},
    {"id": "18.9.33.6.4", "enabled": True, "desc": "Ensure 'Require a password when a computer wakes (plugged in)' is set to 'Enabled' (Automated)"},
    {"id": "18.9.35.1", "enabled": True, "desc": "Ensure 'Configure Offer Remote Assistance' is set to 'Disabled' (Automated)"},
    {"id": "18.9.35.2", "enabled": True, "desc": "Ensure 'Configure Solicited Remote Assistance' is set to 'Disabled' (Automated)"},
    {"id": "18.9.36.1", "enabled": True, "desc": "Ensure 'Enable RPC Endpoint Mapper Client Authentication' is set to 'Enabled' (MS only) (Automated)"},
    {"id": "18.9.39.3", "enabled": True, "desc": "Ensure 'Configure SAM change password RPC methods policy' is set to 'Enabled: Block all change password RPC methods' (MS only) (Automated)"},
    {"id": "18.9.51.1.1", "enabled": True, "desc": "Ensure 'Enable Windows NTP Client' is set to 'Enabled' (Automated)"},
    {"id": "18.9.51.1.2", "enabled": True, "desc": "Ensure 'Enable Windows NTP Server' is set to 'Disabled' (MS only) (Automated)"},
    {"id": "18.10.4.2", "enabled": True, "desc": "Ensure 'Not allow per-user unsigned packages to install by default (requires explicitly allow per install)' is set to 'Enabled' (Automated)"},
    {"id": "18.10.6.1", "enabled": True, "desc": "Ensure 'Allow Microsoft accounts to be optional' is set to 'Enabled' (Automated)"},
    {"id": "18.10.8.1", "enabled": True, "desc": "Ensure 'Disallow Autoplay for non-volume devices' is set to 'Enabled' (Automated)"},
    {"id": "18.10.8.2", "enabled": True, "desc": "Ensure 'Set the default behavior for AutoRun' is set to 'Enabled: Do not execute any autorun commands' (Automated)"},
    {"id": "18.10.8.3", "enabled": True, "desc": "Ensure 'Turn off Autoplay' is set to 'Enabled: All drives' (Automated)"},
    {"id": "18.10.9.1.1", "enabled": True, "desc": "Ensure 'Configure enhanced anti-spoofing' is set to 'Enabled' (Automated)"},
    {"id": "18.10.13.1", "enabled": True, "desc": "Ensure 'Turn off cloud consumer account state content' is set to 'Enabled' (Automated)"},
    {"id": "18.10.13.3", "enabled": True, "desc": "Ensure 'Turn off Microsoft consumer experiences' is set to 'Enabled' (Automated)"},
    {"id": "18.10.14.1", "enabled": True, "desc": "Ensure 'Require pin for pairing' is set to 'Enabled: First Time' OR 'Enabled: Always' (Automated)"},
    {"id": "18.10.15.1", "enabled": True, "desc": "Ensure 'Do not display the password reveal button' is set to 'Enabled' (Automated)"},
    {"id": "18.10.15.2", "enabled": True, "desc": "Ensure 'Enumerate administrator accounts on elevation' is set to 'Disabled' (Automated)"},
    {"id": "18.10.16.1", "enabled": True, "desc": "Ensure 'Allow Diagnostic Data' is set to 'Enabled: Diagnostic data off (not recommended)' or 'Enabled: Send required diagnostic data' (Automated)"},
    {"id": "18.10.16.3", "enabled": True, "desc": "Ensure 'Disable OneSettings Downloads' is set to 'Enabled' (Automated)"},
    {"id": "18.10.16.4", "enabled": True, "desc": "Ensure 'Do not show feedback notifications' is set to 'Enabled' (Automated)"},
    {"id": "18.10.16.5", "enabled": True, "desc": "Ensure 'Enable OneSettings Auditing' is set to 'Enabled' (Automated)"},
    {"id": "18.10.16.6", "enabled": True, "desc": "Ensure 'Limit Diagnostic Log Collection' is set to 'Enabled' (Automated)"},
    {"id": "18.10.16.7", "enabled": True, "desc": "Ensure 'Limit Dump Collection' is set to 'Enabled' (Automated)"},
    {"id": "18.10.18.2", "enabled": True, "desc": "Ensure 'Enable App Installer Experimental Features' is set to 'Disabled' (Automated)"},
    {"id": "18.10.18.3", "enabled": True, "desc": "Ensure 'Enable App Installer Hash Override' is set to 'Disabled' (Automated)"},
    {"id": "18.10.18.4", "enabled": True, "desc": "Ensure 'Enable App Installer Local Archive Malware Scan Override' is set to 'Disabled' (Automated)"},
    {"id": "18.10.18.5", "enabled": True, "desc": "Ensure 'Enable App Installer ms-appinstaller protocol' is set to 'Disabled' (Automated)"},
    {"id": "18.10.18.6", "enabled": True, "desc": "Ensure 'Enable App Installer Microsoft Store Source Certificate Validation Bypass' is set to 'Disabled' (Automated)"},
    {"id": "18.10.26.1.1", "enabled": True, "desc": "Ensure 'Application: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled' (Automated)"},
    {"id": "18.10.26.1.2", "enabled": True, "desc": "Ensure 'Application: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater' (Automated)"},
    {"id": "18.10.26.2.1", "enabled": True, "desc": "Ensure 'Security: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled' (Automated)"},
    {"id": "18.10.26.2.2", "enabled": True, "desc": "Ensure 'Security: Specify the maximum log file size (KB)' is set to 'Enabled: 196,608 or greater' (Automated)"},
    {"id": "18.10.26.3.1", "enabled": True, "desc": "Ensure 'Setup: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled' (Automated)"},
    {"id": "18.10.26.3.2", "enabled": True, "desc": "Ensure 'Setup: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater' (Automated)"},
    {"id": "18.10.26.4.1", "enabled": True, "desc": "Ensure 'System: Control Event Log behavior when the log file reaches its maximum size' is set to 'Disabled' (Automated)"},
    {"id": "18.10.26.4.2", "enabled": True, "desc": "Ensure 'System: Specify the maximum log file size (KB)' is set to 'Enabled: 32,768 or greater' (Automated)"},
    {"id": "18.10.29.2", "enabled": True, "desc": "Ensure 'Do not apply the Mark of the Web tag to files copied from insecure sources' is set to 'Disabled' (Automated)"},
    {"id": "18.10.29.3", "enabled": True, "desc": "Ensure 'Turn off Data Execution Prevention for Explorer' is set to 'Disabled' (Automated)"},
    {"id": "18.10.29.4", "enabled": True, "desc": "Ensure 'Turn off heap termination on corruption' is set to 'Disabled' (Automated)"},
    {"id": "18.10.29.5", "enabled": True, "desc": "Ensure 'Turn off shell protocol protected mode' is set to 'Disabled' (Automated)"},
    {"id": "18.10.42.1", "enabled": True, "desc": "Ensure 'Block all consumer Microsoft account user authentication' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.4.1", "enabled": True, "desc": "Ensure 'Enable EDR in block mode' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.5.1", "enabled": True, "desc": "Ensure 'Configure local setting override for reporting to Microsoft MAPS' is set to 'Disabled' (Automated)"},
    {"id": "18.10.43.6.1.1", "enabled": True, "desc": "Ensure 'Configure Attack Surface Reduction rules' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.6.1.2", "enabled": True, "desc": "Ensure 'Configure Attack Surface Reduction rules: Set the state for each ASR rule' is configured (Automated)"},
    {"id": "18.10.43.6.3.1", "enabled": True, "desc": "Ensure 'Prevent users and apps from accessing dangerous websites' is set to 'Enabled: Block' (Automated)"},
    {"id": "18.10.43.7.1", "enabled": True, "desc": "Ensure 'Enable file hash computation feature' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.10.1", "enabled": True, "desc": "Ensure 'Configure real-time protection and Security Intelligence Updates during OOBE' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.10.2", "enabled": True, "desc": "Ensure 'Scan all downloaded files and attachments' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.10.3", "enabled": True, "desc": "Ensure 'Turn off real-time protection' is set to 'Disabled' (Automated)"},
    {"id": "18.10.43.10.4", "enabled": True, "desc": "Ensure 'Turn on behavior monitoring' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.10.5", "enabled": True, "desc": "Ensure 'Turn on script scanning' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.11.1.1.2", "enabled": True, "desc": "Ensure 'Configure Remote Encryption Protection Mode' is set to 'Enabled: Audit' or higher (Automated)"},
    {"id": "18.10.43.13.1", "enabled": True, "desc": "Ensure 'Scan excluded files and directories during quick scans' is set to 'Enabled: 1' (Automated)"},
    {"id": "18.10.43.13.2", "enabled": True, "desc": "Ensure 'Scan packed executables' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.13.3", "enabled": True, "desc": "Ensure 'Scan removable drives' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.13.4", "enabled": True, "desc": "Ensure 'Trigger a quick scan after X days without any scans' is set to 'Enabled: 7' (Automated)"},
    {"id": "18.10.43.13.5", "enabled": True, "desc": "Ensure 'Turn on e-mail scanning' is set to 'Enabled' (Automated)"},
    {"id": "18.10.43.16", "enabled": True, "desc": "Ensure 'Configure detection for potentially unwanted applications' is set to 'Enabled: Block' (Automated)"},
    {"id": "18.10.43.17", "enabled": True, "desc": "Ensure 'Control whether exclusions are visible to local users' is set to 'Enabled' (Automated)"},
    {"id": "18.10.51.1", "enabled": True, "desc": "Ensure 'Prevent the usage of OneDrive for file storage' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.2.2", "enabled": True, "desc": "Ensure 'Do not allow passwords to be saved' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.3.3.3", "enabled": True, "desc": "Ensure 'Do not allow drive redirection' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.3.9.1", "enabled": True, "desc": "Ensure 'Always prompt for password upon connection' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.3.9.2", "enabled": True, "desc": "Ensure 'Require secure RPC communication' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.3.9.3", "enabled": True, "desc": "Ensure 'Require use of specific security layer for remote (RDP) connections' is set to 'Enabled: SSL' (Automated)"},
    {"id": "18.10.57.3.9.4", "enabled": True, "desc": "Ensure 'Require user authentication for remote connections by using Network Level Authentication' is set to 'Enabled' (Automated)"},
    {"id": "18.10.57.3.9.5", "enabled": True, "desc": "Ensure 'Set client connection encryption level' is set to 'Enabled: High Level' (Automated)"},
    {"id": "18.10.57.3.11.1", "enabled": True, "desc": "Ensure 'Do not delete temp folders upon exit' is set to 'Disabled' (Automated)"},
    {"id": "18.10.57.3.11.2", "enabled": True, "desc": "Ensure 'Do not use temporary folders per session' is set to 'Disabled' (Automated)"},
    {"id": "18.10.58.1", "enabled": True, "desc": "Ensure 'Prevent downloading of enclosures' is set to 'Enabled' (Automated)"},
    {"id": "18.10.58.2", "enabled": True, "desc": "Ensure 'Turn on Basic feed authentication over HTTP' is set to 'Disabled' (Automated)"},
    {"id": "18.10.59.3", "enabled": True, "desc": "Ensure 'Allow indexing of encrypted files' is set to 'Disabled' (Automated)"},
    {"id": "18.10.76.2.1", "enabled": True, "desc": "Ensure 'Configure Windows Defender SmartScreen' is set to 'Enabled: Warn and prevent bypass' (Automated)"},
    {"id": "18.10.80.2", "enabled": True, "desc": "Ensure 'Allow Windows Ink Workspace' is set to 'Enabled: On, but disallow access above lock' OR 'Enabled: Disabled' (Automated)"},
    {"id": "18.10.81.1", "enabled": True, "desc": "Ensure 'Allow user control over installs' is set to 'Disabled' (Automated)"},
    {"id": "18.10.81.2", "enabled": True, "desc": "Ensure 'Always install with elevated privileges' is set to 'Disabled' (Automated)"},
    {"id": "18.10.82.1", "enabled": True, "desc": "Ensure 'Configure the transmission of the user's password in the content of MPR notifications sent by winlogon.' is set to 'Disabled' (Automated)"},
    {"id": "18.10.82.2", "enabled": True, "desc": "Ensure 'Sign-in and lock last interactive user automatically after a restart' is set to 'Disabled' (Automated)"},
    {"id": "18.10.89.1.1", "enabled": True, "desc": "Ensure 'Allow Basic authentication' is set to 'Disabled' (Automated)"},
    {"id": "18.10.89.1.2", "enabled": True, "desc": "Ensure 'Allow unencrypted traffic' is set to 'Disabled' (Automated)"},
    {"id": "18.10.89.1.3", "enabled": True, "desc": "Ensure 'Disallow Digest authentication' is set to 'Enabled' (Automated)"},
    {"id": "18.10.89.2.1", "enabled": True, "desc": "Ensure 'Allow Basic authentication' is set to 'Disabled' (Automated)"},
    {"id": "18.10.89.2.3", "enabled": True, "desc": "Ensure 'Allow unencrypted traffic' is set to 'Disabled' (Automated)"},
    {"id": "18.10.89.2.4", "enabled": True, "desc": "Ensure 'Disallow WinRM from storing RunAs credentials' is set to 'Enabled' (Automated)"},
    {"id": "18.10.92.2.1", "enabled": True, "desc": "Ensure 'Prevent users from modifying settings' is set to 'Enabled' (Automated)"},
    {"id": "18.10.93.1.1", "enabled": True, "desc": "Ensure 'No auto-restart with logged on users for scheduled automatic updates installations' is set to 'Disabled' (Automated)"},
    {"id": "18.10.93.2.1", "enabled": True, "desc": "Ensure 'Configure Automatic Updates' is set to 'Enabled' (Automated)"},
    {"id": "18.10.93.2.2", "enabled": True, "desc": "Ensure 'Configure Automatic Updates: Scheduled install day' is set to '0 - Every day' (Automated)"},
    {"id": "18.10.93.4.1", "enabled": True, "desc": "Ensure 'Manage preview builds' is set to 'Disabled' (Automated)"},
    {"id": "18.10.93.4.2", "enabled": True, "desc": "Ensure 'Select when Preview Builds and Feature Updates are received' is set to 'Enabled: 180 or more days' (Automated)"},
    {"id": "18.10.93.4.3", "enabled": True, "desc": "Ensure 'Select when Quality Updates are received' is set to 'Enabled: 0 days' (Automated)"},
    
    # Section 19
    {"id": "19.5.1.1", "enabled": True, "desc": "Ensure 'Turn off toast notifications on the lock screen' is set to 'Enabled' (Automated)"},
    {"id": "19.7.5.1", "enabled": True, "desc": "Ensure 'Do not preserve zone information in file attachments' is set to 'Disabled' (Automated)"},
    {"id": "19.7.5.2", "enabled": True, "desc": "Ensure 'Notify antivirus programs when opening attachments' is set to 'Enabled' (Automated)"},
    {"id": "19.7.8.1", "enabled": True, "desc": "Ensure 'Configure Windows spotlight on lock screen' is set to 'Disabled' (Automated)"},
    {"id": "19.7.8.2", "enabled": True, "desc": "Ensure 'Do not suggest third-party content in Windows spotlight' is set to 'Enabled' (Automated)"},
    {"id": "19.7.8.5", "enabled": True, "desc": "Turn off Spotlight collection on Desktop' is set to 'Enabled' (Automated)"},
    {"id": "19.7.26.1", "enabled": True, "desc": "Ensure 'Prevent users from sharing files within their profile.' is set to 'Enabled' (Automated)"},
    {"id": "19.7.44.1", "enabled": True, "desc": "Ensure 'Always install with elevated privileges' is set to 'Disabled' (Automated)"},
]